/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.6.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application

    id("io.qameta.allure") version "3.0.1"
    id("io.qameta.allure-report") version "3.0.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(libs.selenide)
    implementation(libs.testng)
    implementation(libs.allure.testng)
    implementation(libs.allure.selenide)
    implementation(libs.retrofit)
    implementation(libs.retrofit.jackson)
    implementation(libs.okhttp.logging)
    implementation(libs.allure.okhttp3)
    testRuntimeOnly(libs.logback.classic)
    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)
    testImplementation(libs.assertj)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

allure {
    version.set("2.43.0")

    adapter {
        frameworks {
            testng {
                enabled.set(true)
            }
        }
    }
}

tasks.named<Test>("test") {
    useTestNG {
        suites("src/test/resources/testng.xml")
    }

    System.getProperties().forEach { (key, value) ->
        systemProperty(key.toString(), value)
    }

    testLogging {
        events("passed", "skipped", "failed")
    }
}

