name: Run tests
run-name: "Run tests (${{ github.run_number }}) on branch [${{ github.ref_name }}] by ${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'browser'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox

      headless:
        description: 'headless'
        required: true
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  automation-tests:
    timeout-minutes: 5
    runs-on: ubuntu-24.04

    steps:
      - name: Print selected parameters to Summary
        run: |
          echo "### Workflow launch parameters" >> $GITHUB_STEP_SUMMARY
          echo "- **browser:** ${{ github.event.inputs.browser }}" >> $GITHUB_STEP_SUMMARY
          echo "- **headless:** ${{ github.event.inputs.headless }}" >> $GITHUB_STEP_SUMMARY

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Allure history
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: allure-history

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Install Xvfb
        if: ${{ github.event.inputs.headless == 'false' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run Tests (UI mode)
        if: ${{ github.event.inputs.headless == 'false' }}
        run: |
          xvfb-run --server-args="-screen 0 1920x1080x24" \
            ./gradlew test \
            -Dbrowser=${{ github.event.inputs.browser }} \
            -Dheadless=${{ github.event.inputs.headless }} \
            --no-configuration-cache

      - name: Run Tests (Headless mode)
        if: ${{ github.event.inputs.headless == 'true' }}
        run: |
          ./gradlew test \
            -Dbrowser=${{ github.event.inputs.browser }} \
            -Dheadless=${{ github.event.inputs.headless }} \
            --no-configuration-cache

      - name: Generate Allure Report
        if: always()
        run: ./gradlew allureReport --no-configuration-cache

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: simple-elf/allure-report-action@v1.14
        with:
          allure_results: app/build/allure-results
          allure_report: app/build/reports/allure-report
          allure_history: allure-history
          keep_reports: 5

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          keep_files: true

      - name: Add Allure Report link to Job Summary
        if: always()
        run: |
          echo "### Allure Test Report for Run #${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
          echo "👉 [https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }}/](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }}/)" >> $GITHUB_STEP_SUMMARY
